import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";

// 101 URL кластера «авто», слитые редиректом в /katalog/navesy/navesy-dlya-mashin/
const MERGED_TO_AVTO = [
  "avtomobilnye-navesy",
  "navesy-dlya-mashin/navesy-dlya-dvuh-mashin", "navesy-dlya-mashin/navesy-dlya-mashin-iz-metalla-i-polikarbonata",
  "navesy-dlya-mashin/navesy-dlya-mashin-iz-metalla", "navesy-dlya-mashin/navesy-dlya-mashin-iz-metallocherepicy",
  "navesy-dlya-mashin/navesy-dlya-mashin-iz-polikarbonata", "navesy-dlya-mashin/navesy-dlya-mashin-v-moskve",
  "navesy-dlya-mashin/navesy-dlya-mashiny-6h6-iz-metalla", "navesy-dlya-mashin/navesy-dlya-mashiny-iz-metalla",
  "navesy-dlya-mashin/navesy-dlya-mashiny-iz-metallicheskogo-profilya", "navesy-dlya-mashin/navesy-dlya-mashiny-iz-polikarbonata-odnoskatnye",
  "navesy-dlya-mashin/navesy-dlya-mashiny-iz-polikarbonata-v-moskve", "navesy-dlya-mashin/navesy-dlya-mashiny-iz-polikarbonata",
  "navesy-dlya-mashin/navesy-dlya-mashiny-iz-profnastila", "navesy-dlya-mashin/navesy-dlya-mashiny-metallicheskie",
  "navesy-dlya-mashin/navesy-dlya-mashiny-na-dache", "navesy-dlya-mashin/navesy-dlya-mashiny-na-dachu-iz-metalla",
  "navesy-dlya-mashin/navesy-dlya-mashiny-na-dachu", "navesy-dlya-mashin/navesy-dlya-mashiny-odnoskatnye",
  "navesy-dlya-mashin/navesy-dlya-mashiny-pod-kljuch", "navesy-dlya-mashin/navesy-dlya-mashiny-s-ploskoj-kryshej",
  "navesy-dlya-mashin/navesy-dlya-mashiny", "navesy-dlya-mashin/navesy-iz-polikarbonata-dlya-dvuh-mashin",
  "navesy-dlya-mashin/navesy-iz-polikarbonata-dlya-mashin-na-dache", "navesy-dlya-mashin/navesy-iz-polikarbonata-dlya-mashin",
  "navesy-dlya-mashin/navesy-iz-polikarbonata-dlya-mashiny", "navesy-dlya-mashin/navesy-iz-polikarbonata-vo-dvore-dlya-mashiny",
  "navesy-dlya-mashin/navesy-na-2-mashiny-iz-polikarbonata", "navesy-dlya-mashin/navesy-na-dve-mashiny",
  "navesy-dlya-mashin/navesy-nad-mashinoj-iz-polikarbonata", "navesy-dlya-mashin/navesy-nad-mashinoj",
  "navesy-dlya-mashin/navesy-pod-2-mashiny", "navesy-dlya-mashin/navesy-pod-dve-mashiny",
  "navesy-dlya-mashin/navesy-pod-mashinu-iz-metalla", "navesy-dlya-mashin/navesy-pod-mashinu-iz-metallocherepicy",
  "navesy-dlya-mashin/navesy-pod-mashinu-iz-polikarbonata", "navesy-dlya-mashin/navesy-pod-mashinu-iz-profnastila",
  "navesy-dlya-mashin/navesy-pod-mashinu-odnoskatnye", "navesy-dlya-mashin/navesy-pod-mashinu",
  "navesy-dlya-mashin/navesy-ulichnye-dlya-mashiny", "navesy-dlya-mashin/polikarbonatnye-navesy-dlya-mashiny",
  "navesy-dlya-mashin/ukrytie-dlya-mashiny-iz-polikarbonata", "navesy-dlya-mashin/ulichnye-navesy-dlya-mashin",
  "avtomobilnye-navesy/avtomobilnye-navesy-iz-polikarbonata", "avtomobilnye-navesy/navesy-avtomobilnye-iz-polikarbonata",
  "avtomobilnye-navesy/navesy-avtomobilnye", "avtomobilnye-navesy/navesy-dlya-2-avtomobilej",
  "avtomobilnye-navesy/navesy-dlya-avto-6-na-6", "avtomobilnye-navesy/navesy-dlya-avto-deshevo",
  "avtomobilnye-navesy/navesy-dlya-avto-iz-polikarbonata", "avtomobilnye-navesy/navesy-dlya-avto-iz-profnastila",
  "avtomobilnye-navesy/navesy-dlya-avto-na-dachu", "avtomobilnye-navesy/navesy-dlya-avto-odnoskatnye",
  "avtomobilnye-navesy/navesy-dlya-avto", "avtomobilnye-navesy/navesy-dlya-avtomashiny",
  "avtomobilnye-navesy/navesy-dlya-avtomobilej-dlya-dachi-iz-polikarbonata", "avtomobilnye-navesy/navesy-dlya-avtomobilej-iz-metalla",
  "avtomobilnye-navesy/navesy-dlya-avtomobilej-iz-polikarbonata", "avtomobilnye-navesy/navesy-dlya-avtomobilej-iz-profnastila",
  "avtomobilnye-navesy/navesy-dlya-avtomobilej-v-moskve-s-ustanovkoj-pod-kljuch", "avtomobilnye-navesy/navesy-dlya-avtomobilej",
  "avtomobilnye-navesy/navesy-dlya-avtomobilya-iz-metallocherepicy", "avtomobilnye-navesy/navesy-dlya-avtomobilya-iz-metallokonstrukcii",
  "avtomobilnye-navesy/navesy-dlya-avtomobilya-iz-metalloprofilya-odnoskatnye", "avtomobilnye-navesy/navesy-dlya-avtomobilya-iz-metalloprofilya",
  "avtomobilnye-navesy/navesy-dlya-avtomobilya-iz-polikarbonata-dlya-dachi", "avtomobilnye-navesy/navesy-dlya-avtomobilya-na-dachu",
  "avtomobilnye-navesy/navesy-dlya-avtomobilya-odnoskatnye", "avtomobilnye-navesy/navesy-dlya-avtomobilya",
  "avtomobilnye-navesy/navesy-dlya-dvuh-avtomobilej", "avtomobilnye-navesy/navesy-na-dva-avtomobilya",
  "avtomobilnye-navesy/navesy-pod-avto-iz-polikarbonata", "avtomobilnye-navesy/navesy-pod-avto",
  "avtomobilnye-navesy/navesy-pod-avtomobil-iz-polikarbonata", "avtomobilnye-navesy/navesy-pod-avtomobil",
  "avtomobilnye-navesy/navesy-polikarbonat-dlya-avtomobilej",
  "odnoskatnye-navesy/odnoskatnye-navesy-dlya-avtomobilya", "odnoskatnye-navesy/odnoskatnye-navesy-dlya-avto",
  "odnoskatnye-navesy/navesy-odnoskatnye-metallicheskie-dlya-mashiny", "odnoskatnye-navesy/navesy-odnoskatnye-dlya-avtomobilej",
  "odnoskatnye-navesy/navesy-odnoskatnye-dlya-avto", "dvuhskatnye-navesy/navesy-dlya-mashin-dvuhskatnye",
  "dvuhskatnye-navesy/navesy-dlya-avtomobilej-dvuhskatnye", "metallicheskie-navesy/metallicheskie-navesy-pod-mashinu",
  "metallicheskie-navesy/metallicheskie-navesy-dlya-mashiny-s-polikarbonatom", "metallicheskie-navesy/metallicheskie-navesy-dlya-mashiny",
  "metallicheskie-navesy/metallicheskie-navesy-dlya-mashin", "metallicheskie-navesy/metallicheskie-navesy-dlya-avtomobilej",
  "deshevye-navesy-iz-polikarbonata/deshevye-navesy-dlya-mashin", "deshevye-navesy-iz-polikarbonata/deshevye-navesy-dlya-avtomobilej",
  "navesy-dlya-dachi/dachnye-navesy-dlya-mashiny", "navesy-dlya-dachi/dachnye-navesy-dlya-avtomobilya",
  "krytye-navesy/krytye-navesy-dlya-avtomobilya", "drugie/kovanye-navesy-dlya-mashin",
  "drugie/avtonavesy-iz-polikarbonata", "drugie/avtonavesy",
  "navesy-iz-polikarbonata-dlya-avtomobilej", "navesy-iz-polikarbonata-dlya-avto",
  "navesy-iz-polikarbonata-pod-avtomobil", "navesy-iz-polikarbonata-pod-avto",
  "navesy-iz-polikarbonata-dlya-dachi-pod-mashinu",
  "garazhi-iz-polikarbonata",
];

export default defineConfig({
  site: "https://33navesa.ru",
  output: "static",
  integrations: [tailwind(), sitemap({
    // страницы-заглушки редиректов — не для индекса
    filter: (page) => !page.includes("montazh-2") && !page.includes("navesy-dlya-mangala") && !MERGED_TO_AVTO.some((s) => page.includes(s)),
  })],
  trailingSlash: "always",
});
